- hosts: web
  sudo: true
  tasks:
    - name: add a new user      #Linuxユーザの作成
      user: name=test_ohwaki state=present group=wheel

    - name: add a new user      #Linuxユーザのグループ変更
      user: name=test_ohwaki state=present

    - name: add authorized keys #.ssh以下にauthorized_keysファイルの作成
      shell: sudo cp -R ~/.ssh /home/test_ohwaki/.ssh

    - name: add authorized keys #.ssh以下にauthorized_keysの権限変更
      shell: sudo chown -R test_ohwaki:test_ohwaki ~test_ohwaki/.ssh

    - name: add authorized keys #.ssh以下にauthorized_keysの権限変更
      shell: sudo chmod -R go-rwx ~test_ohwaki/.ssh