- hosts: web
  sudo: true
  tasks:
    - name: add a new user      #Linuxユーザの作成
      user: name=test_ohwaki state=present

    - name: mkdir .ssh          #.sshフォルダの作成
      file: dest=/home/test_ohwaki/.ssh/ state=directory owner=test_ohwaki group=test_ohwaki mode=700

    - name: add authorized keys #.ssh以下にauthorized_keysファイルの作成
      copy: src=/home/ec2-user/.ssh/authorized_keys dest=/home/test_ohwaki/.ssh/authorized_keys state=touch owner=test_ohwaki group=test_ohwaki mode=600