- hosts: web
  become: true
  tasks:
    - name: add a new user      #Linuxユーザの作成
      user: name=test_ohwaki state=present group=wheel

    - name: add a new user      #Linuxユーザのグループ変更
      user: name=test_ohwaki state=present

    - name: mkdir .ssh          #.sshフォルダの作成
      file: dest=/home/test_ohwaki/.ssh/ state=directory owner=test_ohwaki group=test_ohwaki mode=700

    - name: add authorized keys #.ssh以下にauthorized_keysファイルの作成
      copy: src=~/.ssh/authorized_keys dest=/home/test_ohwaki/.ssh/authorized_keys owner=test_ohwaki group=test_ohwaki mode=600