- hosts: web
  sudo: true
  tasks:
    - name: add a new user      #Linuxユーザの作成
      shell: sudo useradd test_ohwaki2

    - name: add a new user      #Linuxユーザのグループ変更
      shell: sudo usermod -aG wheel test_ohwaki2

    - name: add authorized keys #.ssh以下にauthorized_keysファイルの作成
      shell: sudo cp -R /home/ec2-user/.ssh /home/test_ohwaki2/.ssh

    - name: add authorized keys #.ssh以下にauthorized_keysの権限変更
      shell: sudo chown -R test_ohwaki2:test_ohwaki2 ~test_ohwaki2/.ssh

    - name: add authorized keys #.ssh以下にauthorized_keysの権限変更
      shell: sudo chmod -R go-rwx ~test_ohwaki2/.ssh