- hosts: web1
  become: true
  tasks:
    - name: apache start #apache 起動
      shell: echo 'bzuh6sdgjhd' | sudo -S service httpd start

    - name: apache restart #apache 再起動
      shell: echo 'bzuh6sdgjhd' | sudo -S service httpd restart
